import type { FoodItem } from "./types";

// Comprehensive food database with accurate macro data per 100g
// Sources: USDA FoodData Central, verified nutritional databases
export const FOOD_DATABASE: FoodItem[] = [
  // ===== GRAINS & CEREALS =====
  {
    id: "oats_rolled",
    name: "Rolled Oats",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 389,
      proteinG: 16.9,
      carbsG: 66.3,
      fatG: 6.9,
      fiberG: 10.6,
      sugarG: 0.0,
    },
  },
  {
    id: "quinoa_cooked",
    name: "Quinoa, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 120,
      proteinG: 4.4,
      carbsG: 21.3,
      fatG: 1.9,
      fiberG: 2.8,
      sugarG: 0.9,
    },
  },
  {
    id: "brown_rice_cooked",
    name: "Brown Rice, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 111,
      proteinG: 2.6,
      carbsG: 23.0,
      fatG: 0.9,
      fiberG: 1.8,
      sugarG: 0.4,
    },
  },
  {
    id: "white_rice_cooked",
    name: "White Rice, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 130,
      proteinG: 2.7,
      carbsG: 28.2,
      fatG: 0.3,
      fiberG: 0.4,
      sugarG: 0.1,
    },
  },
  {
    id: "whole_wheat_bread",
    name: "Whole Wheat Bread",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 247,
      proteinG: 13.0,
      carbsG: 41.0,
      fatG: 4.2,
      fiberG: 7.0,
      sugarG: 4.3,
    },
  },
  {
    id: "white_bread",
    name: "White Bread",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 265,
      proteinG: 9.0,
      carbsG: 49.0,
      fatG: 3.2,
      fiberG: 2.7,
      sugarG: 5.0,
    },
  },
  {
    id: "pasta_cooked",
    name: "Pasta, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 131,
      proteinG: 5.0,
      carbsG: 25.1,
      fatG: 1.1,
      fiberG: 1.8,
      sugarG: 0.8,
    },
  },
  {
    id: "barley_cooked",
    name: "Barley, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 123,
      proteinG: 2.3,
      carbsG: 28.2,
      fatG: 0.4,
      fiberG: 3.8,
      sugarG: 0.3,
    },
  },

  // ===== PROTEINS - MEAT & POULTRY =====
  {
    id: "chicken_breast_cooked",
    name: "Chicken Breast, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 165,
      proteinG: 31.0,
      carbsG: 0.0,
      fatG: 3.6,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },
  {
    id: "chicken_thigh_cooked",
    name: "Chicken Thigh, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 209,
      proteinG: 26.0,
      carbsG: 0.0,
      fatG: 12.0,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },
  {
    id: "turkey_breast_cooked",
    name: "Turkey Breast, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 157,
      proteinG: 29.8,
      carbsG: 0.0,
      fatG: 3.6,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },
  {
    id: "beef_lean_cooked",
    name: "Beef, lean cuts, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 250,
      proteinG: 26.0,
      carbsG: 0.0,
      fatG: 15.0,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },
  {
    id: "pork_loin_cooked",
    name: "Pork Loin, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 242,
      proteinG: 27.0,
      carbsG: 0.0,
      fatG: 14.0,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },
  {
    id: "lamb_lean_cooked",
    name: "Lamb, lean cuts, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 294,
      proteinG: 25.6,
      carbsG: 0.0,
      fatG: 21.0,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },

  // ===== PROTEINS - FISH & SEAFOOD =====
  {
    id: "salmon_cooked",
    name: "Salmon, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 208,
      proteinG: 25.0,
      carbsG: 0.0,
      fatG: 12.0,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },
  {
    id: "tuna_canned",
    name: "Tuna, canned in water",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 116,
      proteinG: 26.0,
      carbsG: 0.0,
      fatG: 0.8,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },
  {
    id: "cod_cooked",
    name: "Cod, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 105,
      proteinG: 23.0,
      carbsG: 0.0,
      fatG: 0.9,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },
  {
    id: "shrimp_cooked",
    name: "Shrimp, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 99,
      proteinG: 24.0,
      carbsG: 0.2,
      fatG: 0.3,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },
  {
    id: "tilapia_cooked",
    name: "Tilapia, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 96,
      proteinG: 20.1,
      carbsG: 0.0,
      fatG: 2.3,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },

  // ===== PROTEINS - EGGS & DAIRY =====
  {
    id: "egg_whole",
    name: "Egg, whole",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 155,
      proteinG: 12.6,
      carbsG: 0.8,
      fatG: 11.3,
      fiberG: 0.0,
      sugarG: 0.4,
    },
  },
  {
    id: "egg_white",
    name: "Egg White",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 52,
      proteinG: 11.0,
      carbsG: 0.7,
      fatG: 0.2,
      fiberG: 0.0,
      sugarG: 0.7,
    },
  },
  {
    id: "egg_yolk",
    name: "Egg Yolk",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 322,
      proteinG: 15.9,
      carbsG: 0.6,
      fatG: 26.5,
      fiberG: 0.0,
      sugarG: 0.1,
    },
  },
  {
    id: "milk_skim",
    name: "Milk, skim",
    basePortion: { quantity: 100, unit: "ml" },
    densityGPerMl: 1.035,
    macrosPerBase: {
      caloriesKcal: 34,
      proteinG: 3.4,
      carbsG: 5.0,
      fatG: 0.1,
      fiberG: 0.0,
      sugarG: 5.0,
    },
  },
  {
    id: "milk_whole",
    name: "Milk, whole",
    basePortion: { quantity: 100, unit: "ml" },
    densityGPerMl: 1.032,
    macrosPerBase: {
      caloriesKcal: 61,
      proteinG: 3.2,
      carbsG: 4.8,
      fatG: 3.3,
      fiberG: 0.0,
      sugarG: 4.8,
    },
  },
  {
    id: "yogurt_greek_plain",
    name: "Greek Yogurt, plain",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 59,
      proteinG: 10.0,
      carbsG: 3.6,
      fatG: 0.4,
      fiberG: 0.0,
      sugarG: 3.2,
    },
  },
  {
    id: "yogurt_regular_plain",
    name: "Yogurt, plain",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 61,
      proteinG: 3.5,
      carbsG: 4.7,
      fatG: 3.3,
      fiberG: 0.0,
      sugarG: 4.7,
    },
  },
  {
    id: "cheese_cheddar",
    name: "Cheddar Cheese",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 403,
      proteinG: 25.0,
      carbsG: 1.3,
      fatG: 33.0,
      fiberG: 0.0,
      sugarG: 0.5,
    },
  },
  {
    id: "cheese_mozzarella",
    name: "Mozzarella Cheese",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 280,
      proteinG: 28.0,
      carbsG: 2.2,
      fatG: 17.0,
      fiberG: 0.0,
      sugarG: 1.0,
    },
  },
  {
    id: "cottage_cheese",
    name: "Cottage Cheese",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 98,
      proteinG: 11.1,
      carbsG: 3.4,
      fatG: 4.3,
      fiberG: 0.0,
      sugarG: 2.7,
    },
  },

  // ===== LEGUMES & BEANS =====
  {
    id: "black_beans_cooked",
    name: "Black Beans, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 132,
      proteinG: 8.9,
      carbsG: 23.7,
      fatG: 0.5,
      fiberG: 8.7,
      sugarG: 0.3,
    },
  },
  {
    id: "chickpeas_cooked",
    name: "Chickpeas, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 164,
      proteinG: 8.9,
      carbsG: 27.4,
      fatG: 2.6,
      fiberG: 7.6,
      sugarG: 4.8,
    },
  },
  {
    id: "lentils_cooked",
    name: "Lentils, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 116,
      proteinG: 9.0,
      carbsG: 20.1,
      fatG: 0.4,
      fiberG: 7.9,
      sugarG: 1.8,
    },
  },
  {
    id: "kidney_beans_cooked",
    name: "Kidney Beans, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 127,
      proteinG: 8.7,
      carbsG: 23.4,
      fatG: 0.5,
      fiberG: 6.4,
      sugarG: 0.3,
    },
  },
  {
    id: "pinto_beans_cooked",
    name: "Pinto Beans, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 143,
      proteinG: 9.0,
      carbsG: 26.2,
      fatG: 0.6,
      fiberG: 9.0,
      sugarG: 0.4,
    },
  },

  // ===== NUTS & SEEDS =====
  {
    id: "almonds",
    name: "Almonds",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 579,
      proteinG: 21.2,
      carbsG: 21.7,
      fatG: 49.9,
      fiberG: 12.5,
      sugarG: 4.8,
    },
  },
  {
    id: "walnuts",
    name: "Walnuts",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 654,
      proteinG: 15.2,
      carbsG: 13.7,
      fatG: 65.2,
      fiberG: 6.7,
      sugarG: 2.6,
    },
  },
  {
    id: "peanuts",
    name: "Peanuts",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 567,
      proteinG: 25.8,
      carbsG: 16.1,
      fatG: 49.2,
      fiberG: 8.5,
      sugarG: 4.7,
    },
  },
  {
    id: "cashews",
    name: "Cashews",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 553,
      proteinG: 18.2,
      carbsG: 30.2,
      fatG: 43.8,
      fiberG: 3.3,
      sugarG: 5.9,
    },
  },
  {
    id: "chia_seeds",
    name: "Chia Seeds",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 486,
      proteinG: 17.0,
      carbsG: 42.1,
      fatG: 30.7,
      fiberG: 34.4,
      sugarG: 0.0,
    },
  },
  {
    id: "flaxseeds",
    name: "Flaxseeds",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 534,
      proteinG: 18.3,
      carbsG: 28.9,
      fatG: 42.2,
      fiberG: 27.3,
      sugarG: 1.6,
    },
  },
  {
    id: "sunflower_seeds",
    name: "Sunflower Seeds",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 584,
      proteinG: 20.8,
      carbsG: 20.0,
      fatG: 51.5,
      fiberG: 8.6,
      sugarG: 2.6,
    },
  },

  // ===== VEGETABLES =====
  {
    id: "broccoli_raw",
    name: "Broccoli, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 34,
      proteinG: 2.8,
      carbsG: 7.0,
      fatG: 0.4,
      fiberG: 2.6,
      sugarG: 1.5,
    },
  },
  {
    id: "spinach_raw",
    name: "Spinach, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 23,
      proteinG: 2.9,
      carbsG: 3.6,
      fatG: 0.4,
      fiberG: 2.2,
      sugarG: 0.4,
    },
  },
  {
    id: "kale_raw",
    name: "Kale, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 49,
      proteinG: 4.3,
      carbsG: 8.8,
      fatG: 0.9,
      fiberG: 3.6,
      sugarG: 1.3,
    },
  },
  {
    id: "carrots_raw",
    name: "Carrots, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 41,
      proteinG: 0.9,
      carbsG: 9.6,
      fatG: 0.2,
      fiberG: 2.8,
      sugarG: 4.7,
    },
  },
  {
    id: "bell_pepper_raw",
    name: "Bell Pepper, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 20,
      proteinG: 0.9,
      carbsG: 4.6,
      fatG: 0.2,
      fiberG: 1.7,
      sugarG: 2.4,
    },
  },
  {
    id: "tomatoes_raw",
    name: "Tomatoes, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 18,
      proteinG: 0.9,
      carbsG: 3.9,
      fatG: 0.2,
      fiberG: 1.2,
      sugarG: 2.6,
    },
  },
  {
    id: "cucumber_raw",
    name: "Cucumber, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 16,
      proteinG: 0.7,
      carbsG: 3.6,
      fatG: 0.1,
      fiberG: 0.5,
      sugarG: 1.7,
    },
  },
  {
    id: "onions_raw",
    name: "Onions, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 40,
      proteinG: 1.1,
      carbsG: 9.3,
      fatG: 0.1,
      fiberG: 1.7,
      sugarG: 4.7,
    },
  },
  {
    id: "garlic_raw",
    name: "Garlic, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 149,
      proteinG: 6.4,
      carbsG: 33.1,
      fatG: 0.5,
      fiberG: 2.1,
      sugarG: 1.0,
    },
  },
  {
    id: "mushrooms_raw",
    name: "Mushrooms, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 22,
      proteinG: 3.1,
      carbsG: 3.3,
      fatG: 0.3,
      fiberG: 1.0,
      sugarG: 1.7,
    },
  },

  // ===== FRUITS =====
  {
    id: "banana_raw",
    name: "Banana, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 89,
      proteinG: 1.1,
      carbsG: 22.8,
      fatG: 0.3,
      fiberG: 2.6,
      sugarG: 12.2,
    },
  },
  {
    id: "apple_raw",
    name: "Apple, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 52,
      proteinG: 0.3,
      carbsG: 13.8,
      fatG: 0.2,
      fiberG: 2.4,
      sugarG: 10.4,
    },
  },
  {
    id: "orange_raw",
    name: "Orange, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 47,
      proteinG: 0.9,
      carbsG: 11.8,
      fatG: 0.1,
      fiberG: 2.4,
      sugarG: 9.4,
    },
  },
  {
    id: "strawberries_raw",
    name: "Strawberries, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 32,
      proteinG: 0.7,
      carbsG: 7.7,
      fatG: 0.3,
      fiberG: 2.0,
      sugarG: 4.9,
    },
  },
  {
    id: "blueberries_raw",
    name: "Blueberries, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 57,
      proteinG: 0.7,
      carbsG: 14.5,
      fatG: 0.3,
      fiberG: 2.4,
      sugarG: 10.0,
    },
  },
  {
    id: "grapes_raw",
    name: "Grapes, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 62,
      proteinG: 0.6,
      carbsG: 16.0,
      fatG: 0.2,
      fiberG: 0.9,
      sugarG: 16.0,
    },
  },
  {
    id: "avocado_raw",
    name: "Avocado, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 160,
      proteinG: 2.0,
      carbsG: 8.5,
      fatG: 14.7,
      fiberG: 6.7,
      sugarG: 0.7,
    },
  },
  {
    id: "mango_raw",
    name: "Mango, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 60,
      proteinG: 0.8,
      carbsG: 15.0,
      fatG: 0.4,
      fiberG: 1.6,
      sugarG: 13.7,
    },
  },
  {
    id: "pineapple_raw",
    name: "Pineapple, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 50,
      proteinG: 0.5,
      carbsG: 13.1,
      fatG: 0.1,
      fiberG: 1.4,
      sugarG: 9.9,
    },
  },

  // ===== TUBERS & ROOTS =====
  {
    id: "potato_baked",
    name: "Potato, baked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 93,
      proteinG: 2.5,
      carbsG: 21.2,
      fatG: 0.1,
      fiberG: 2.2,
      sugarG: 1.2,
    },
  },
  {
    id: "sweet_potato_baked",
    name: "Sweet Potato, baked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 90,
      proteinG: 2.0,
      carbsG: 20.7,
      fatG: 0.2,
      fiberG: 3.3,
      sugarG: 6.5,
    },
  },
  {
    id: "carrots_cooked",
    name: "Carrots, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 35,
      proteinG: 0.8,
      carbsG: 8.2,
      fatG: 0.2,
      fiberG: 3.0,
      sugarG: 3.9,
    },
  },

  // ===== OILS & FATS =====
  {
    id: "olive_oil",
    name: "Olive Oil",
    basePortion: { quantity: 100, unit: "ml" },
    densityGPerMl: 0.92,
    macrosPerBase: {
      caloriesKcal: 884,
      proteinG: 0.0,
      carbsG: 0.0,
      fatG: 100.0,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },
  {
    id: "coconut_oil",
    name: "Coconut Oil",
    basePortion: { quantity: 100, unit: "ml" },
    densityGPerMl: 0.92,
    macrosPerBase: {
      caloriesKcal: 862,
      proteinG: 0.0,
      carbsG: 0.0,
      fatG: 100.0,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },
  {
    id: "butter",
    name: "Butter",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 717,
      proteinG: 0.9,
      carbsG: 0.1,
      fatG: 81.1,
      fiberG: 0.0,
      sugarG: 0.1,
    },
  },
  {
    id: "ghee",
    name: "Ghee",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 900,
      proteinG: 0.0,
      carbsG: 0.0,
      fatG: 100.0,
      fiberG: 0.0,
      sugarG: 0.0,
    },
  },

  // ===== CONDIMENTS & SAUCES =====
  {
    id: "ketchup",
    name: "Ketchup",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 102,
      proteinG: 1.2,
      carbsG: 24.8,
      fatG: 0.2,
      fiberG: 0.3,
      sugarG: 22.8,
    },
  },
  {
    id: "mayonnaise",
    name: "Mayonnaise",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 680,
      proteinG: 1.0,
      carbsG: 0.6,
      fatG: 75.0,
      fiberG: 0.0,
      sugarG: 0.6,
    },
  },
  {
    id: "mustard",
    name: "Mustard",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 66,
      proteinG: 4.4,
      carbsG: 5.8,
      fatG: 4.4,
      fiberG: 4.0,
      sugarG: 0.9,
    },
  },
  {
    id: "soy_sauce",
    name: "Soy Sauce",
    basePortion: { quantity: 100, unit: "ml" },
    densityGPerMl: 1.18,
    macrosPerBase: {
      caloriesKcal: 53,
      proteinG: 8.1,
      carbsG: 4.9,
      fatG: 0.1,
      fiberG: 0.8,
      sugarG: 0.4,
    },
  },

  // ===== SWEETENERS =====
  {
    id: "honey",
    name: "Honey",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 304,
      proteinG: 0.3,
      carbsG: 82.4,
      fatG: 0.0,
      fiberG: 0.2,
      sugarG: 82.1,
    },
  },
  {
    id: "maple_syrup",
    name: "Maple Syrup",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 260,
      proteinG: 0.0,
      carbsG: 67.0,
      fatG: 0.0,
      fiberG: 0.0,
      sugarG: 67.0,
    },
  },
  {
    id: "sugar_white",
    name: "White Sugar",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 387,
      proteinG: 0.0,
      carbsG: 100.0,
      fatG: 0.0,
      fiberG: 0.0,
      sugarG: 100.0,
    },
  },
  {
    id: "brown_sugar",
    name: "Brown Sugar",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 380,
      proteinG: 0.0,
      carbsG: 98.0,
      fatG: 0.0,
      fiberG: 0.0,
      sugarG: 98.0,
    },
  },

  // ===== PROCESSED FOODS =====
  {
    id: "breadcrumbs",
    name: "Breadcrumbs",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 395,
      proteinG: 13.4,
      carbsG: 72.0,
      fatG: 5.3,
      fiberG: 4.5,
      sugarG: 6.2,
    },
  },
  {
    id: "flour_all_purpose",
    name: "All-Purpose Flour",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 364,
      proteinG: 10.3,
      carbsG: 76.3,
      fatG: 1.0,
      fiberG: 2.7,
      sugarG: 0.3,
    },
  },
  {
    id: "flour_whole_wheat",
    name: "Whole Wheat Flour",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 340,
      proteinG: 13.2,
      carbsG: 72.0,
      fatG: 2.5,
      fiberG: 10.7,
      sugarG: 0.4,
    },
  },
  {
    id: "cornmeal",
    name: "Cornmeal",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 365,
      proteinG: 8.1,
      carbsG: 77.0,
      fatG: 3.6,
      fiberG: 7.3,
      sugarG: 1.9,
    },
  },

  // ===== ADDITIONAL VEGETABLES =====
  {
    id: "cauliflower_raw",
    name: "Cauliflower, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 25,
      proteinG: 1.9,
      carbsG: 5.0,
      fatG: 0.3,
      fiberG: 2.0,
      sugarG: 1.9,
    },
  },
  {
    id: "zucchini_raw",
    name: "Zucchini, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 17,
      proteinG: 1.2,
      carbsG: 3.1,
      fatG: 0.3,
      fiberG: 1.0,
      sugarG: 2.5,
    },
  },
  {
    id: "eggplant_raw",
    name: "Eggplant, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 25,
      proteinG: 1.0,
      carbsG: 6.0,
      fatG: 0.2,
      fiberG: 3.0,
      sugarG: 3.5,
    },
  },
  {
    id: "asparagus_raw",
    name: "Asparagus, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 20,
      proteinG: 2.2,
      carbsG: 3.9,
      fatG: 0.1,
      fiberG: 2.1,
      sugarG: 1.9,
    },
  },
  {
    id: "brussels_sprouts_raw",
    name: "Brussels Sprouts, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 43,
      proteinG: 3.4,
      carbsG: 9.0,
      fatG: 0.3,
      fiberG: 3.8,
      sugarG: 2.2,
    },
  },

  // ===== ADDITIONAL FRUITS =====
  {
    id: "pear_raw",
    name: "Pear, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 57,
      proteinG: 0.4,
      carbsG: 15.2,
      fatG: 0.1,
      fiberG: 3.1,
      sugarG: 9.8,
    },
  },
  {
    id: "peach_raw",
    name: "Peach, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 39,
      proteinG: 0.9,
      carbsG: 10.0,
      fatG: 0.3,
      fiberG: 1.5,
      sugarG: 8.4,
    },
  },
  {
    id: "plum_raw",
    name: "Plum, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 46,
      proteinG: 0.7,
      carbsG: 11.4,
      fatG: 0.3,
      fiberG: 1.4,
      sugarG: 9.9,
    },
  },
  {
    id: "cherries_raw",
    name: "Cherries, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 50,
      proteinG: 1.1,
      carbsG: 12.2,
      fatG: 0.3,
      fiberG: 1.6,
      sugarG: 8.5,
    },
  },
  {
    id: "kiwi_raw",
    name: "Kiwi, raw",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 61,
      proteinG: 1.1,
      carbsG: 14.7,
      fatG: 0.5,
      fiberG: 3.0,
      sugarG: 9.0,
    },
  },

  // ===== ADDITIONAL NUTS & SEEDS =====
  {
    id: "pistachios",
    name: "Pistachios",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 560,
      proteinG: 20.2,
      carbsG: 27.2,
      fatG: 45.3,
      fiberG: 10.6,
      sugarG: 7.6,
    },
  },
  {
    id: "pecans",
    name: "Pecans",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 691,
      proteinG: 9.2,
      carbsG: 13.9,
      fatG: 72.0,
      fiberG: 9.6,
      sugarG: 4.0,
    },
  },
  {
    id: "macadamia_nuts",
    name: "Macadamia Nuts",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 718,
      proteinG: 7.9,
      carbsG: 13.8,
      fatG: 75.8,
      fiberG: 8.6,
      sugarG: 4.6,
    },
  },
  {
    id: "pumpkin_seeds",
    name: "Pumpkin Seeds",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 559,
      proteinG: 19.0,
      carbsG: 54.0,
      fatG: 19.0,
      fiberG: 18.0,
      sugarG: 1.0,
    },
  },

  // ===== ADDITIONAL LEGUMES =====
  {
    id: "navy_beans_cooked",
    name: "Navy Beans, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 140,
      proteinG: 8.2,
      carbsG: 26.1,
      fatG: 0.6,
      fiberG: 10.5,
      sugarG: 0.3,
    },
  },
  {
    id: "lima_beans_cooked",
    name: "Lima Beans, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 115,
      proteinG: 7.8,
      carbsG: 20.9,
      fatG: 0.4,
      fiberG: 7.0,
      sugarG: 2.9,
    },
  },
  {
    id: "split_peas_cooked",
    name: "Split Peas, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 118,
      proteinG: 8.3,
      carbsG: 21.4,
      fatG: 0.4,
      fiberG: 8.3,
      sugarG: 2.9,
    },
  },

  // ===== ADDITIONAL GRAINS =====
  {
    id: "bulgur_cooked",
    name: "Bulgur, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 83,
      proteinG: 3.1,
      carbsG: 17.6,
      fatG: 0.2,
      fiberG: 4.5,
      sugarG: 0.1,
    },
  },
  {
    id: "farro_cooked",
    name: "Farro, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 127,
      proteinG: 5.0,
      carbsG: 26.0,
      fatG: 1.0,
      fiberG: 3.0,
      sugarG: 0.0,
    },
  },
  {
    id: "millet_cooked",
    name: "Millet, cooked",
    basePortion: { quantity: 100, unit: "g" },
    macrosPerBase: {
      caloriesKcal: 119,
      proteinG: 3.5,
      carbsG: 23.7,
      fatG: 1.0,
      fiberG: 1.3,
      sugarG: 0.1,
    },
  },
];

// Helper function to get food by ID
export function getFoodById(id: string): FoodItem | undefined {
  return FOOD_DATABASE.find(food => food.id === id);
}

// Helper function to search foods by name
export function searchFoods(query: string): FoodItem[] {
  const lowerQuery = query.toLowerCase();
  return FOOD_DATABASE.filter(food => 
    food.name.toLowerCase().includes(lowerQuery)
  );
}

// Helper function to get foods by category
export function getFoodsByCategory(category: string): FoodItem[] {
  const categoryMap: Record<string, string[]> = {
    "grains": ["oats_rolled", "quinoa_cooked", "brown_rice_cooked", "white_rice_cooked", "whole_wheat_bread", "white_bread", "pasta_cooked", "barley_cooked"],
    "proteins": ["chicken_breast_cooked", "chicken_thigh_cooked", "turkey_breast_cooked", "beef_lean_cooked", "pork_loin_cooked", "lamb_lean_cooked", "salmon_cooked", "tuna_canned", "cod_cooked", "shrimp_cooked", "tilapia_cooked", "egg_whole", "egg_white", "egg_yolk"],
    "dairy": ["milk_skim", "milk_whole", "yogurt_greek_plain", "yogurt_regular_plain", "cheese_cheddar", "cheese_mozzarella", "cottage_cheese"],
    "legumes": ["black_beans_cooked", "chickpeas_cooked", "lentils_cooked", "kidney_beans_cooked", "pinto_beans_cooked"],
    "nuts_seeds": ["almonds", "walnuts", "peanuts", "cashews", "chia_seeds", "flaxseeds", "sunflower_seeds"],
    "vegetables": ["broccoli_raw", "spinach_raw", "kale_raw", "carrots_raw", "bell_pepper_raw", "tomatoes_raw", "cucumber_raw", "onions_raw", "garlic_raw", "mushrooms_raw"],
    "fruits": ["banana_raw", "apple_raw", "orange_raw", "strawberries_raw", "blueberries_raw", "grapes_raw", "avocado_raw", "mango_raw", "pineapple_raw"],
    "tubers": ["potato_baked", "sweet_potato_baked", "carrots_cooked"],
    "oils_fats": ["olive_oil", "coconut_oil", "butter", "ghee"],
    "condiments": ["ketchup", "mayonnaise", "mustard", "soy_sauce"],
    "sweeteners": ["honey", "maple_syrup", "sugar_white", "brown_sugar"],
    "processed": ["breadcrumbs", "flour_all_purpose", "flour_whole_wheat", "cornmeal"]
  };
  
  const foodIds = categoryMap[category.toLowerCase()] || [];
  return FOOD_DATABASE.filter(food => foodIds.includes(food.id));
}

// Helper function to get all categories
export function getFoodCategories(): string[] {
  return ["grains", "proteins", "dairy", "legumes", "nuts_seeds", "vegetables", "fruits", "tubers", "oils_fats", "condiments", "sweeteners", "processed"];
}

// Export the database size for reference
export const DATABASE_SIZE = FOOD_DATABASE.length;
