import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <nav className="border-b border-foreground/15 p-3 text-sm">
          <div className="mx-auto flex max-w-3xl items-center justify-between">
            <Link href="/" className="font-semibold">
              Nutritionist Co‑Pilot
            </Link>
            <Link href="/chat" className="underline">
              Chat
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
